version: '2.1'
orbs:
 # import CircleCI's aws-cli orb
 aws-cli: circleci/aws-cli@5.1.2
jobs:
 aws-example:
   docker:
     - image: cimg/aws:2022.06
   steps:
     - checkout
     # run the aws-cli/setup command from the orb
     - aws-cli/setup:
         role_arn: arn:aws:iam::916370597556:role/circle-ci_trust_policy_role
         profile_name: default
     - run:
         name: login S3 and LS
         command: |
           # must use same profile specified in the step above       
           aws s3 ls --region us-east-1
workflows:
  version: 2
  build_and_push:
   jobs:
     - aws-example
