version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      # Setup remote Docker environment
      - setup_remote_docker

      # Setup AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      # Authenticate to AWS ECR
      - run:
          name: Authenticate to AWS ECR
          command: |
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ECR_URL

      # Build Docker Image
      - run:
          name: Build Docker Image
          command: docker build -t dev/circleci-repo:$CIRCLE_SHA1 .

      # Push Docker Image to ECR
      - aws-ecr/build-and-push-image:
          repo: dev/circleci-repo
          tag: $CIRCLE_SHA1

workflows:
  version: 2
  build_and_push_image:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - main
